import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const mainfont = localFont({
  src: "./fonts/SFUIText-Bold.ttf",
  variable: "--font-main",
  weight: "100 900",
});
const lite = localFont({
  src: "./fonts/SFUIText-Light.ttf",
  variable: "--font-lite",
  weight: "100 900",
});
const Bold = localFont({
  src: "./fonts/SFUIText-Heavy.ttf",
  variable: "--font-bold",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Gilbert Garcia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${
          (mainfont.variable, lite.variable, Bold.variable)
        } font-main scroll-smooth overflow-x-hidden bg-neutral antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
